version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aeportal
    ports:
      - "3307:3306"
    healthcheck:
      test: mysql aeportal --user=root --password='root' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5 

  web:
    build:
      context: ./portal
    environment:
      - SPRING_DB_URL=jdbc:mysql://db:3306/aeportal
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:9000"
